# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/local/RadioScatter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/local/RadioScatter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/RadioScatter/CMakeFiles /usr/local/RadioScatter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/RadioScatter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RadioScatterEvent

# Build rule for target.
RadioScatterEvent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RadioScatterEvent
.PHONY : RadioScatterEvent

# fast build rule for target.
RadioScatterEvent/fast:
	$(MAKE) -f CMakeFiles/RadioScatterEvent.dir/build.make CMakeFiles/RadioScatterEvent.dir/build
.PHONY : RadioScatterEvent/fast

#=============================================================================
# Target rules for targets named G__RadioScatterEvent

# Build rule for target.
G__RadioScatterEvent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 G__RadioScatterEvent
.PHONY : G__RadioScatterEvent

# fast build rule for target.
G__RadioScatterEvent/fast:
	$(MAKE) -f CMakeFiles/G__RadioScatterEvent.dir/build.make CMakeFiles/G__RadioScatterEvent.dir/build
.PHONY : G__RadioScatterEvent/fast

G__RadioScatterEvent.o: G__RadioScatterEvent.cxx.o

.PHONY : G__RadioScatterEvent.o

# target to build an object file
G__RadioScatterEvent.cxx.o:
	$(MAKE) -f CMakeFiles/RadioScatterEvent.dir/build.make CMakeFiles/RadioScatterEvent.dir/G__RadioScatterEvent.cxx.o
.PHONY : G__RadioScatterEvent.cxx.o

G__RadioScatterEvent.i: G__RadioScatterEvent.cxx.i

.PHONY : G__RadioScatterEvent.i

# target to preprocess a source file
G__RadioScatterEvent.cxx.i:
	$(MAKE) -f CMakeFiles/RadioScatterEvent.dir/build.make CMakeFiles/RadioScatterEvent.dir/G__RadioScatterEvent.cxx.i
.PHONY : G__RadioScatterEvent.cxx.i

G__RadioScatterEvent.s: G__RadioScatterEvent.cxx.s

.PHONY : G__RadioScatterEvent.s

# target to generate assembly for a file
G__RadioScatterEvent.cxx.s:
	$(MAKE) -f CMakeFiles/RadioScatterEvent.dir/build.make CMakeFiles/RadioScatterEvent.dir/G__RadioScatterEvent.cxx.s
.PHONY : G__RadioScatterEvent.cxx.s

RadioScatter.o: RadioScatter.cc.o

.PHONY : RadioScatter.o

# target to build an object file
RadioScatter.cc.o:
	$(MAKE) -f CMakeFiles/RadioScatterEvent.dir/build.make CMakeFiles/RadioScatterEvent.dir/RadioScatter.cc.o
.PHONY : RadioScatter.cc.o

RadioScatter.i: RadioScatter.cc.i

.PHONY : RadioScatter.i

# target to preprocess a source file
RadioScatter.cc.i:
	$(MAKE) -f CMakeFiles/RadioScatterEvent.dir/build.make CMakeFiles/RadioScatterEvent.dir/RadioScatter.cc.i
.PHONY : RadioScatter.cc.i

RadioScatter.s: RadioScatter.cc.s

.PHONY : RadioScatter.s

# target to generate assembly for a file
RadioScatter.cc.s:
	$(MAKE) -f CMakeFiles/RadioScatterEvent.dir/build.make CMakeFiles/RadioScatterEvent.dir/RadioScatter.cc.s
.PHONY : RadioScatter.cc.s

RadioScatterEvent.o: RadioScatterEvent.cc.o

.PHONY : RadioScatterEvent.o

# target to build an object file
RadioScatterEvent.cc.o:
	$(MAKE) -f CMakeFiles/RadioScatterEvent.dir/build.make CMakeFiles/RadioScatterEvent.dir/RadioScatterEvent.cc.o
.PHONY : RadioScatterEvent.cc.o

RadioScatterEvent.i: RadioScatterEvent.cc.i

.PHONY : RadioScatterEvent.i

# target to preprocess a source file
RadioScatterEvent.cc.i:
	$(MAKE) -f CMakeFiles/RadioScatterEvent.dir/build.make CMakeFiles/RadioScatterEvent.dir/RadioScatterEvent.cc.i
.PHONY : RadioScatterEvent.cc.i

RadioScatterEvent.s: RadioScatterEvent.cc.s

.PHONY : RadioScatterEvent.s

# target to generate assembly for a file
RadioScatterEvent.cc.s:
	$(MAKE) -f CMakeFiles/RadioScatterEvent.dir/build.make CMakeFiles/RadioScatterEvent.dir/RadioScatterEvent.cc.s
.PHONY : RadioScatterEvent.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... RadioScatterEvent"
	@echo "... G__RadioScatterEvent"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... G__RadioScatterEvent.o"
	@echo "... G__RadioScatterEvent.i"
	@echo "... G__RadioScatterEvent.s"
	@echo "... RadioScatter.o"
	@echo "... RadioScatter.i"
	@echo "... RadioScatter.s"
	@echo "... RadioScatterEvent.o"
	@echo "... RadioScatterEvent.i"
	@echo "... RadioScatterEvent.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

